### PR TITLE
Add option to disable hearbeat logs. 

### PR DESCRIPTION
**Pull request by TheYande**
checks for an env variable and if its false or doesnt exist it doesnt log the heartbeat aknolwagted 

btw why havent you done this yet

### CODE REVIEW

**Comment by RedGuy12** [comment]
> btw why havent you done this yet

you never asked

btw yk it already does ignore heartbeat logs in node_env == "production"

anyway, i'd prefer this to be an option, and that way you could just default it to `process.env.NODE_ENV !== "production"`

**Comment by RedGuy12** [comment]
🤷‍♂️

**Comment by TheYande** [comment]
🤷‍♂️

**Comment by RedGuy12** [comment]
> btw yk it already does ignore heartbeat logs in node_env == "production"
> 
> anyway, i'd prefer this to be an option, and that way you could just default it to `process.env.NODE_ENV !== "production"`

bump

**Comment by RedGuy12** [comment]
@TheYande

**Review by RedGuy12 — CHANGES_REQUESTED** [review]
^^^

**Comment by RedGuy12** [comment]
bump

**Pull request closed without merging**
